### ISSUE TITLE
Dependency error in robobrowser library!

### ISSUE THREAD

**Issue by frapecar** [garmin-data/garmdown#1]
robobrowser library is using an old dependency (wertzeug). In new version  cached_property is not in werkzeug package it is in werkzeug.utils.
You can customize it locally and then garmdown works well.
Lets wait for a robobrowser update...

`make PYTHON_BIN_ARGS='sync -c test-resources/garmdown.conf' run
make[1]: Entering directory '/garmdown'
running src/bin/garmdown
Traceback (most recent call last):
  File "src/bin/garmdown", line 3, in <module>
    from zensols.garmdown import ConfAppCommandLine
  File "/garmdown/src/python/zensols/garmdown/__init__.py", line 3, in <module>
    from zensols.garmdown.fetcher import *
  File "/garmdown/src/python/zensols/garmdown/fetcher.py", line 6, in <module>
    from robobrowser import RoboBrowser
  File "/usr/local/lib/python3.7/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.7/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py)
make[1]: *** [/garmdown/zenbuild/src/mk/python.mk:92: pyrun] Error 1
make[1]: Leaving directory '/garmdown'
make: *** [makefile:22: sync] Error 2`

**Comment by plandes** [comment]
This is [fixed](https://github.com/garmin-data/garmdown/commit/59d741f7c3fb7169195710efc24211cc5ec3343d) in the [latest release](https://github.com/garmin-data/garmdown/releases/tag/v0.0.4).  Thanks for the issue and the help resolving it.

**Comment by plandes** [comment]
Closing due to inactivity.
