### ISSUE TITLE
AttributeError: module 'zensols' has no attribute 'actioncli'

### ISSUE THREAD

**Issue by pierretamisier** [garmin-data/garmdown#4]
Hi folks!

I'm installed garmdown thru pip as instructed in the readme however I'm trying to figure out why I can't even start it up.

`pierre@pierre-thinkpad:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic`

`pierre@pierre-thinkpad:~$ garmdown --version
Traceback (most recent call last):
  File "/home/pierre/.local/bin/garmdown", line 7, in <module>
    from zensols.garmdown import main
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/garmdown/__init__.py", line 1, in <module>
    from zensols.garmdown.config import *
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/garmdown/config.py", line 2, in <module>
    from zensols.actioncli import ExtendedInterpolationConfig
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/actioncli/__init__.py", line 4, in <module>
    from zensols.actioncli.persist import *
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/actioncli/persist.py", line 18, in <module>
    import zensols.actioncli.time as time
AttributeError: module 'zensols' has no attribute 'actioncli'
`

In the meantime, I'm gonna look at compiling from source instead.

**Comment by plandes** [comment]
Hi @pierretamisier 

Did you install via pip or from the source?  My recommendation is to install via pip with (and uninstall first):
```bash
pip uninstall zensols.garmdown
pip install zensols.garmdown
```

**Comment by pierretamisier** [comment]
Hello @plandes ! Thanks for helping!
My issue is related to the pip install, not the source.

Here's where I stand but I'll keep digging and share my findings.

```
pierre@pierre-thinkpad:~$ pip uninstall zensols.garmdown
Found existing installation: zensols.garmdown 0.0.4
Uninstalling zensols.garmdown-0.0.4:
  Would remove:
    /home/pierre/.local/bin/garmdown
    /home/pierre/.local/lib/python3.6/site-packages/zensols.garmdown-0.0.4.dist-info/*
    /home/pierre/.local/lib/python3.6/site-packages/zensols/garmdown/*
Proceed (y/n)? y
  Successfully uninstalled zensols.garmdown-0.0.4

pierre@pierre-thinkpad:~$ pip install zensols.garmdown
Defaulting to user installation because normal site-packages is not writeable
Collecting zensols.garmdown
  Downloading zensols.garmdown-0.0.6-py3-none-any.whl (21 kB)
Requirement already satisfied: google-auth>=1.6.2 in ./.local/lib/python3.6/site-packages (from zensols.garmdown) (1.12.0)
Requirement already satisfied: google-api-python-client>=1.7.7 in ./.local/lib/python3.6/site-packages (from zensols.garmdown) (1.8.0)
Requirement already satisfied: oauth2client>=4.1.3 in ./.local/lib/python3.6/site-packages (from zensols.garmdown) (4.1.3)
Requirement already satisfied: robobrowser==0.5.3 in ./.local/lib/python3.6/site-packages (from zensols.garmdown) (0.5.3)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in ./.local/lib/python3.6/site-packages (from zensols.garmdown) (0.0.3)
Requirement already satisfied: httplib2>=0.12.0 in ./.local/lib/python3.6/site-packages (from zensols.garmdown) (0.17.0)
Collecting zensols.util>=1.2.3
  Downloading zensols.util-1.2.5-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 1.0 MB/s 
Requirement already satisfied: setuptools>=40.3.0 in ./.local/lib/python3.6/site-packages (from google-auth>=1.6.2->zensols.garmdown) (46.1.3)
Requirement already satisfied: rsa<4.1,>=3.1.4 in ./.local/lib/python3.6/site-packages (from google-auth>=1.6.2->zensols.garmdown) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.6/site-packages (from google-auth>=1.6.2->zensols.garmdown) (0.2.8)
Requirement already satisfied: six>=1.9.0 in ./.local/lib/python3.6/site-packages (from google-auth>=1.6.2->zensols.garmdown) (1.11.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in ./.local/lib/python3.6/site-packages (from google-auth>=1.6.2->zensols.garmdown) (4.0.0)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in ./.local/lib/python3.6/site-packages (from google-api-python-client>=1.7.7->zensols.garmdown) (3.0.1)
Requirement already satisfied: google-api-core<2dev,>=1.13.0 in ./.local/lib/python3.6/site-packages (from google-api-python-client>=1.7.7->zensols.garmdown) (1.16.0)
Requirement already satisfied: pyasn1>=0.1.7 in ./.local/lib/python3.6/site-packages (from oauth2client>=4.1.3->zensols.garmdown) (0.4.8)
Requirement already satisfied: requests>=2.6.0 in ./.local/lib/python3.6/site-packages (from robobrowser==0.5.3->zensols.garmdown) (2.19.1)
Requirement already satisfied: beautifulsoup4>=4.3.2 in ./.local/lib/python3.6/site-packages (from robobrowser==0.5.3->zensols.garmdown) (4.8.2)
Requirement already satisfied: Werkzeug>=0.10.4 in ./.local/lib/python3.6/site-packages (from robobrowser==0.5.3->zensols.garmdown) (1.0.0)
Requirement already satisfied: configparser==3.5.0 in ./.local/lib/python3.6/site-packages (from zensols.util>=1.2.3->zensols.garmdown) (3.5.0)
Requirement already satisfied: PyYAML>=5.1 in ./.local/lib/python3.6/site-packages (from zensols.util>=1.2.3->zensols.garmdown) (5.3.1)
Requirement already satisfied: parse>=1.9.0 in ./.local/lib/python3.6/site-packages (from zensols.util>=1.2.3->zensols.garmdown) (1.15.0)
Requirement already satisfied: pytz in ./.local/lib/python3.6/site-packages (from google-api-core<2dev,>=1.13.0->google-api-python-client>=1.7.7->zensols.garmdown) (2019.3)
Requirement already satisfied: protobuf>=3.4.0 in ./.local/lib/python3.6/site-packages (from google-api-core<2dev,>=1.13.0->google-api-python-client>=1.7.7->zensols.garmdown) (3.11.3)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in ./.local/lib/python3.6/site-packages (from google-api-core<2dev,>=1.13.0->google-api-python-client>=1.7.7->zensols.garmdown) (1.51.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.6/site-packages (from requests>=2.6.0->robobrowser==0.5.3->zensols.garmdown) (2019.11.28)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./.local/lib/python3.6/site-packages (from requests>=2.6.0->robobrowser==0.5.3->zensols.garmdown) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python3.6/site-packages (from requests>=2.6.0->robobrowser==0.5.3->zensols.garmdown) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in ./.local/lib/python3.6/site-packages (from requests>=2.6.0->robobrowser==0.5.3->zensols.garmdown) (2.7)
Requirement already satisfied: soupsieve>=1.2 in ./.local/lib/python3.6/site-packages (from beautifulsoup4>=4.3.2->robobrowser==0.5.3->zensols.garmdown) (2.0)
Installing collected packages: zensols.util, zensols.garmdown
Successfully installed zensols.garmdown-0.0.6 zensols.util-1.2.5
WARNING: You are using pip version 20.0.2; however, version 20.2.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

pierre@pierre-thinkpad:~$ garmdown --version
Traceback (most recent call last):
  File "/home/pierre/.local/bin/garmdown", line 5, in <module>
    from zensols.garmdown import main
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/garmdown/__init__.py", line 1, in <module>
    from zensols.garmdown.config import *
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/garmdown/config.py", line 2, in <module>
    from zensols.config import ExtendedInterpolationConfig
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/config/__init__.py", line 3, in <module>
    from zensols.config.factory import *
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/config/factory.py", line 17, in <module>
    from zensols.persist import persisted, PersistedWork
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/persist/__init__.py", line 2, in <module>
    from zensols.persist.stash import *
  File "/home/pierre/.local/lib/python3.6/site-packages/zensols/persist/stash.py", line 8, in <module>
    from dataclasses import dataclass, field, InitVar
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by plandes** [comment]
Either upgrade to Python 3.7 or downgrade the version of `zensols.garmdown`.  I'm pretty sure you'll have to do the former since the newer version of the library uses the newer Garmin API.

**Comment by pierretamisier** [comment]
I upgraded to Python 3.8. Still some import issues. Im super confused.

```
pierre@pierre-thinkpad:~/Downloads$ pip uninstall zensols.garmdown
WARNING: Skipping zensols.garmdown as it is not installed.
pierre@pierre-thinkpad:~/Downloads$ pip3 uninstall zensols.garmdown
WARNING: Skipping zensols.garmdown as it is not installed.
```
```
pierre@pierre-thinkpad:~/Downloads$ pip3 install zensols.garmdown
Defaulting to user installation because normal site-packages is not writeable
Collecting zensols.garmdown
  Using cached zensols.garmdown-0.0.6-py3-none-any.whl (21 kB)
Collecting google-auth>=1.6.2
  Downloading google_auth-1.20.0-py2.py3-none-any.whl (91 kB)
     |████████████████████████████████| 91 kB 1.5 MB/s 
Collecting robobrowser==0.5.3
  Using cached robobrowser-0.5.3.tar.gz (22 kB)
Collecting google-auth-httplib2>=0.0.3
  Downloading google_auth_httplib2-0.0.4-py2.py3-none-any.whl (9.1 kB)
Collecting httplib2>=0.12.0
  Downloading httplib2-0.18.1-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 1.2 MB/s 
Collecting zensols.util>=1.2.3
  Using cached zensols.util-1.2.5-py3-none-any.whl (40 kB)
Collecting oauth2client>=4.1.3
  Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
Collecting google-api-python-client>=1.7.7
  Downloading google_api_python_client-1.10.0-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 2.0 MB/s 
Collecting setuptools>=40.3.0
  Using cached setuptools-49.2.1-py3-none-any.whl (789 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.5"
  Downloading rsa-4.6-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 1.3 MB/s 
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from google-auth>=1.6.2->zensols.garmdown) (1.11.0)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting Werkzeug>=0.10.4
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 14.3 MB/s 
Collecting beautifulsoup4>=4.3.2
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 11.7 MB/s 
Requirement already satisfied: requests>=2.6.0 in /usr/lib/python3/dist-packages (from robobrowser==0.5.3->zensols.garmdown) (2.18.4)
Collecting configparser==3.5.0
  Using cached configparser-3.5.0.tar.gz (39 kB)
Collecting parse>=1.9.0
  Downloading parse-1.16.0.tar.gz (30 kB)
Collecting PyYAML>=5.1
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting pyasn1>=0.1.7
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting uritemplate<4dev,>=3.0.0
  Using cached uritemplate-3.0.1-py2.py3-none-any.whl (15 kB)
Collecting google-api-core<2dev,>=1.18.0
  Downloading google_api_core-1.22.0-py2.py3-none-any.whl (91 kB)
     |████████████████████████████████| 91 kB 1.2 MB/s 
Collecting soupsieve>1.2
  Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from google-api-core<2dev,>=1.18.0->google-api-python-client>=1.7.7->zensols.garmdown) (2018.3)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Downloading googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 3.1 MB/s 
Collecting protobuf>=3.12.0
  Downloading protobuf-3.12.4-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 11.9 MB/s 
Building wheels for collected packages: robobrowser, configparser, parse, PyYAML
  Building wheel for robobrowser (setup.py) ... done
  Created wheel for robobrowser: filename=robobrowser-0.5.3-py3-none-any.whl size=16456 sha256=660103fd0f98f152aa958b63204f688012210c5bc2b5b6aa93302f3d7dd18a7b
  Stored in directory: /home/pierre/.cache/pip/wheels/29/f5/46/15be591132a6321c7c4f02e7c6c54efdc016b847f5642143f2
  Building wheel for configparser (setup.py) ... done
  Created wheel for configparser: filename=configparser-3.5.0-py3-none-any.whl size=26375 sha256=7ce589b640a8c0d98304770d45920da908a004ba7aa19aabc8ffe9999ae98b82
  Stored in directory: /home/pierre/.cache/pip/wheels/5d/e3/bb/8b1c37164107de95ec6b43136ffe01685b8d32dfb0440760ef
  Building wheel for parse (setup.py) ... done
  Created wheel for parse: filename=parse-1.16.0-py3-none-any.whl size=30713 sha256=3cf29279330eb184958aa7f31d9f83603874831587b556982da9392ba2f7e24d
  Stored in directory: /home/pierre/.cache/pip/wheels/00/59/a2/6f966e476bc0f84d821e8347c8ad94726b1e0ba8a2b2c9b25e
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl size=45918 sha256=ea698af7d1b58fe5b43d00a70b9211f2b08e99738cc55e51f9e360670160f6eb
  Stored in directory: /home/pierre/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
Successfully built robobrowser configparser parse PyYAML
Installing collected packages: setuptools, pyasn1, rsa, pyasn1-modules, cachetools, google-auth, Werkzeug, soupsieve, beautifulsoup4, robobrowser, httplib2, google-auth-httplib2, configparser, parse, PyYAML, zensols.util, oauth2client, uritemplate, protobuf, googleapis-common-protos, google-api-core, google-api-python-client, zensols.garmdown
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

launchpadlib 1.10.6 requires testresources, which is not installed.
Successfully installed PyYAML-5.3.1 Werkzeug-1.0.1 beautifulsoup4-4.9.1 cachetools-4.1.1 configparser-3.5.0 google-api-core-1.22.0 google-api-python-client-1.10.0 google-auth-1.20.0 google-auth-httplib2-0.0.4 googleapis-common-protos-1.52.0 httplib2-0.18.1 oauth2client-4.1.3 parse-1.16.0 protobuf-3.12.4 pyasn1-0.4.8 pyasn1-modules-0.2.8 robobrowser-0.5.3 rsa-4.6 setuptools-49.2.1 soupsieve-2.0.1 uritemplate-3.0.1 zensols.garmdown-0.0.6 zensols.util-1.2.5
```
```
pierre@pierre-thinkpad:~/Downloads$ garmdown
Traceback (most recent call last):
  File "/home/pierre/.local/bin/garmdown", line 5, in <module>
    from zensols.garmdown import main
  File "/home/pierre/.local/lib/python3.8/site-packages/zensols/garmdown/__init__.py", line 3, in <module>
    from zensols.garmdown.fetcher import *
  File "/home/pierre/.local/lib/python3.8/site-packages/zensols/garmdown/fetcher.py", line 6, in <module>
    from robobrowser import RoboBrowser
  File "/home/pierre/.local/lib/python3.8/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/home/pierre/.local/lib/python3.8/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/home/pierre/.local/lib/python3.8/site-packages/werkzeug/__init__.py) 
```

**Comment by plandes** [comment]
This error should have been fixed in the last release.  I have updated a dependency and pushed a new release ty PyPi.  Try the following:

```bash
pip uninstall robobrowsker
pip install -U zensols.garmdown
```

and let me know what happens.
